
# ===================================
# “作弊”功能
[Cheat]
# 解锁游戏里所有可能的跑图券
TicketUnlock=true
# 解锁游戏里所有的区域，包括非当前版本的（并不会帮你跑完）
MapUnlock=true
# 不需要万分也可以进宴会场
UnlockUtage=true
# 恢复 SDGA 的自动播放（Home）和暂停（Enter）按键
DebugFeature=true

# ===================================
# 用户体验改进
[UX]
# 跳过日服启动时候的 WARNING 界面
SkipWarningScreen=true
# 单人模式，不显示 2P
SinglePlayer=true
# 登录完成后直接进入选歌界面
SkipToMusicSelection=false
# 把右上角的版本更改为自定义文本
CustomVersionString=""
# 已弃用，请使用 LoadAssetsPng
# LoadJacketPng=true
# 通过游戏目录下 `LocalAssets\000000（歌曲 ID）.png` 加载封面，自制谱用
LoadAssetsPng=true
# 如果没有 dat 格式的 BGA 的话，就用歌曲的封面做背景，而不是显示迪拉熊的笑脸
# 请和 `LoadJacketPng` 一起用
LoadLocalBga=true
# 长按 Service 键或者键盘上的 “7” 键（ADX 默认固件下箭头键中间的圆形按键）可以：
# - 跳过登录过程中的界面直接进入选歌界面
# - 在选歌界面直接结束游戏
# 在游玩界面，按一下 “7” 或者 Service 键重开当前的歌，按 1P 的“选择”键立即结束当前乐曲
# 打完最后一个音符之后也可以
QuickSkip=true
# 优化图片资源的加载，就算没有 AssetBundleImages.manifest 也可以正常加载 ab 格式的图片资源
# 导入了删除曲包之类的话，应该需要开启这个
LoadAssetBundleWithoutManifest=true
# 跳过登录 / 注册游戏时候可能的 “发现了新的区域哟” “乐曲增加” “有活动哟” 之类的提示
SkipEventInfo=true
# 在 `LocalAssets\Mai2Cue` 这个目录下放置了旧版游戏的 Mai2Cue.{acb,awb} 并重命名的话，可以在播放游戏 BGM 的时候随机播放这里面的旧版游戏 BGM
# 和 2P 模式有冲突，如果你没有开启 'SinglePlayer' 的话，请关闭这个
RandomBgm=false
# 在闲置时的演示画面上播放紫谱而不是绿谱
DemoMaster=true
# 在游戏闲置或者玩家登录的时候执行指定的命令脚本
# 比如说可以在游戏闲置是降低显示器的亮度
ExecOnIdle=""
ExecOnEntry=""
# 关掉那些游戏中的倒计时
# 如果你没有开启 'SinglePlayer' 的话，不建议开这个，不过要开的话也不是不可以
ExtendTimer=true
# 打完一首歌的时候立即向服务器保存成绩
ImmediateSave=true
# 防止你不小心按到 Test 键，Test 键需要长按 1 秒才能生效
TestProof=false
# 自定义拍照的店铺名称
# 同时在 SDGA 中会启用店铺名称的显示（但是不会在游戏里有设置）
CustomPlaceName=""
# 选歌界面按下 Service 键或者键盘上的 “7” 键（ADX 默认固件下箭头键中间的圆形按键）切换自制谱的显示和隐藏
# 是否是自制谱的判断方式是 Axxx 目录里没有 DataConfig.xml 或 OfficialChartsMark.txt 就认为这个目录里是自制谱
HideSelfMadeCharts=true
# 选歌界面显示选择的歌曲的详情
SelectionDetail=true

# ===================================
# 一些性能优化
[Performance]
# 在自检界面，每个屏幕结束的时候都会等两秒才进入下一个屏幕，很浪费时间
# 开了这个选项之后就不会等了
ImproveLoadSpeed=true

# ===================================
# 修复一些潜在的问题
[Fix]
# 原先如果你的账号版本比当前游戏设定的版本高的话，就会不能登录
# 开了这个选项之后就可以登录了，不过你的账号版本还是会被设定为当前游戏的版本
SkipVersionCheck=true
# 如果你在用未经修改的客户端，会默认加密到服务器的连接，而连接私服的时候不应该加密
# 开了这个选项之后就不会加密连接了，同时也会移除不同版本的客户端可能会对 API 接口加的后缀
# 正常情况下，请保持这个选项开启
RemoveEncryption=true
# 如果要配置店内招募的话，应该要把这个关闭
ForceAsServer=true
# 强制改为免费游玩（FreePlay）
ForceFreePlay=true
# 强制付费游玩并锁定 24 个币，和 ForceFreePlay 冲突
ForcePaidPlay=false
# 增加更多待命的音符贴图，防止奇怪的自制谱用完音符贴图池
ExtendNotesPool=128

[Utils]
# 登录时将 UserID 输出到日志
LogUserId=false
# 全局增加 A 判，单位和游戏里一样
JudgeAdjustA=0.0
# 全局增加 B 判，单位和游戏里一样
JudgeAdjustB=0.0
# 触摸屏延迟，单位为毫秒，一秒 = 1000 毫秒。必须是整数
TouchDelay=0

[TouchSensitivity]
# 是否启用自定义灵敏度
# 这里启用之后 Test 里的就不再起作用了
# 这里禁用之后就还是可以用 Test 里的调
Enable=false
# 在 Test 模式下调整的灵敏度不是线性的
# A 区默认灵敏度 90, 80, 70, 60, 50, 40, 30, 26, 23, 20, 10
# 其他区域默认灵敏度 70, 60, 50, 40, 30, 20, 15, 10, 5, 1, 1
# Test 里设置的 0 对应的是 40, 20 这一档，-5 是 90, 70，+5 是 10, 1
# Test 里的数字越大，这里的数字越小，对于官机来说，灵敏度更大
# 而 ADX 的灵敏度是反的，所以对于 ADX，这里的数字越大，灵敏度越大
A1=40
A2=40
A3=40
A4=40
A5=40
A6=40
A7=40
A8=40
B1=20
B2=20
B3=20
B4=20
B5=20
B6=20
B7=20
B8=20
C1=20
C2=20
D1=20
D2=20
D3=20
D4=20
D5=20
D6=20
D7=20
D8=20
E1=20
E2=20
E3=20
E4=20
E5=20
E6=20
E7=20
E8=20
